version: '3.8'

services:
  web:
    container_name: 'web'
    build:
      context: ./front
      # target: runner
    volumes:
      - .:/app
#    command: yarn start
    ports:
      - "4000:80"
    environment:
      NODE_ENV: development

  backend:
    container_name: 'backend'
    restart: always
    build: .
    ports:
      - "8080:8080"


  loki:
    image: grafana/loki:latest
    container_name: loki
    user: root
    ports:
      - "3100:3100"
    volumes:
      - ./loki-data:/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log  # Монтируем логи из системы
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - loki

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"  # HTTPS UI
      - "9000:9000"  # (опционально) старый UI
      - "8000:8000"  # Edge Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300

networks:
  monitoring:

volumes:
  grafana-data:
  portainer_data: