version: '3.8'

networks:
  loki:

services:
  web:
    container_name: 'web'
    build:
      context: ./front
      # target: runner
    volumes:
      - .:/app
#    command: yarn start
    ports:
      - "4000:80"
    environment:
      NODE_ENV: development

  backend:
    container_name: 'backend'
    restart: always
    build: .
    ports:
      - "8080:8080"


  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    volumes:
      - /root/promtailloki/loki:/etc/loki
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
      - /root/promtailloki/promtail:/etc/promtail
      - ./promtail-config.yaml:/etc/loki/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki