version: '3.8'

services:
  web:
    container_name: 'web'
    build:
      context: ./front
      # target: runner
    volumes:
      - .:/app
#    command: yarn start
    ports:
      - "4000:80"
    environment:
      NODE_ENV: development

  backend:
    container_name: 'backend'
    restart: always
    build: .
    ports:
      - "8080:8080"


  loki:
      image: grafana/loki:2.9.2
      container_name: loki
      ports:
        - "3100:3100"
      volumes:
        - ./loki-config.yaml:/etc/loki/loki-config.yaml
      command: -config.file=/etc/loki/loki-config.yaml
      networks:
        - monitoring

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log  # Монтируем логи из системы
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    depends_on:
      - loki

networks:
  monitoring:

volumes:
  grafana-data: