server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: docker-logs-backend
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
    relabel_configs:
      - source_labels: [ backend ]
        target_label: backend

  - job_name: 'docker-containers'
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          container_name: backend
          __path__: /var/log/containers/*.log

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          job: node